[build]
  command = ""
  publish = "."
  functions = "netlify/functions"

# 1. Règle API (pour /api/login, /api/execute, etc.)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 2. Règle pour LA PAGE de connexion
[[redirects]]
  from = "/login"
  to = "/login/index.html"
  status = 200
  
# 3. Règle de Fallback (SPA) pour le terminal principal
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200